/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AllowedClass */

#ifndef _Included_AllowedClass
#define _Included_AllowedClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AllowedClass
 * Method:    asSealedInst
 * Signature: ()LSealedClass;
 */
JNIEXPORT jobject JNICALL Java_AllowedClass_asSealedInst
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
